"""Run reconnaissance for Nasdaq scraping requirements.

Usage:
    python3 scripts/recon_nasdaq.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from nasdaq_scraper.recon import TickerRecon
from nasdaq_scraper.recon import run_recon_for_ticker


def build_markdown_report(results: list[TickerRecon]) -> str:
    """Render a concise markdown report from reconnaissance findings."""
    lines: list[str] = []
    lines.append("# Reconnaissance report")
    lines.append("")
    lines.append("This report is auto-generated by `scripts/recon_nasdaq.py`.")
    lines.append("")

    for result in results:
        lines.append(f"## Ticker `{result.ticker}`")
        lines.append("")
        lines.append(f"- Page URL: `{result.page_url}`")
        lines.append(f"- HTTP status: `{result.page_status_code}`")
        lines.append(f"- HTML size: `{result.html_size}` bytes")
        lines.append(f"- Quote component found: `{result.has_quote_component}`")
        lines.append(f"- Quote skeleton found: `{result.has_quote_skeleton}`")
        lines.append(f"- Price literal in static HTML: `{result.has_price_literal}`")
        lines.append(f"- ETF headings found in static HTML: `{result.has_etf_heading_in_html}`")
        lines.append("")

        lines.append("### Embedded API hosts")
        lines.append("")
        if result.api_settings_hosts:
            for host in result.api_settings_hosts:
                lines.append(f"- `{host}`")
        else:
            lines.append("- None detected")
        lines.append("")

        lines.append("### API probe results")
        lines.append("")
        for probe in result.api_probes:
            lines.append(
                "- "
                f"`{probe.endpoint_name}` | `{probe.status_code}` | ok=`{probe.ok}` | "
                f"json=`{probe.json_detected}` | `{probe.url}`"
            )
            if probe.data_keys:
                lines.append(f"- data keys: `{', '.join(probe.data_keys)}`")
        lines.append("")

    lines.append("## Selector candidates")
    lines.append("")
    selector_payload = results[0].selector_candidates if results else {}
    for key, candidates in selector_payload.items():
        lines.append(f"### {key}")
        lines.append("")
        for candidate in candidates:
            lines.append(f"- `{candidate}`")
        lines.append("")

    lines.append("## Strategy recommendation")
    lines.append("")
    lines.append("- Use API-first extraction for quote metrics (`info` endpoint).")
    lines.append("- Keep HTML selectors for structural checks and fallback.")
    lines.append(
        "- Use Playwright network capture only if ETF tables are not present in static HTML and "
        "API endpoints for holdings cannot be reached reliably."
    )
    lines.append("- Keep selector constants isolated in one module for future HTML changes.")
    lines.append("")

    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description="Run Nasdaq reconnaissance for selected tickers.")
    parser.add_argument("--tickers", nargs="+", default=["baba", "aapl", "msft"])
    parser.add_argument("--language", default="es")
    parser.add_argument(
        "--output-json",
        default=str(ROOT / "docs" / "reconnaissance" / "findings.json"),
    )
    parser.add_argument(
        "--output-md",
        default=str(ROOT / "docs" / "reconnaissance" / "findings.md"),
    )
    return parser.parse_args()


def main() -> int:
    """Execute reconnaissance and write reports."""
    args = parse_args()
    results = [run_recon_for_ticker(ticker=ticker, language=args.language) for ticker in args.tickers]

    json_path = Path(args.output_json)
    md_path = Path(args.output_md)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    md_path.parent.mkdir(parents=True, exist_ok=True)

    payload = {"results": [result.to_dict() for result in results]}
    json_path.write_text(json.dumps(payload, indent=2, ensure_ascii=True) + "\n")
    md_path.write_text(build_markdown_report(results) + "\n")

    print(f"Wrote JSON findings to {json_path}")
    print(f"Wrote markdown findings to {md_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
